[package]
name = "iyes_bevy_extras"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10", default-features = false }

[features]
default = [ "bevy_ui", "2d" ]
bevy_ui = [
    "bevy/bevy_render",
    "bevy/bevy_core_pipeline",
    "bevy/bevy_ui",
]
2d = [
    "bevy/bevy_render",
    "bevy/bevy_core_pipeline",
    "bevy/bevy_sprite",
    "bevy/bevy_winit",
]
