[package]
name = "iyes_bevy_util"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", default-features = false }
iyes_loopless = { version = "0.9", optional = true }

[features]
default = [ "bevy_ui", "2d", "iyes_loopless" ]
bevy_ui = [
    "bevy/bevy_ui",
]
2d = [
    "bevy/bevy_sprite",
    "bevy/bevy_winit",
]
