[package]
name = "iyes_bevy_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", default-features = false }

[features]
bevy_ui = [
    "bevy/bevy_ui",
]
2d = [
    "bevy/bevy_sprite",
    "bevy/bevy_winit",
]
